### ISSUE TITLE
コメント統合でlink_idに文字列を使えない

### ISSUE THREAD

**Issue by RyujiAMANO** [XoopsX/d3forum#6]
コメント統合でlink_idに文字列を使いたかったので

D3commentAbstractのvalidadte_idにあるコメントの通りオーバーライドして文字列を使えるようにしたのですが、コメント投稿時にmain/post.php 370行目でint型に型変換されてしまい、投稿後のリダイレクトに失敗します。

D3commentAbstract
```
// if you want to allow "string id", override it
function validate_id( $link_id )
{
	$ret = intval( $link_id ) ;
	if( $ret <= 0 ) return false ;
	return $ret ;
}
```

main/post.php 
```
		// naao added Nov.2012 for check auth for parent entry
		if( is_object( $d3com ) && method_exists( $d3com, 'validate_users2notify') ) {
			$external_link_id = (int)$external_link_id;
			if( $external_link_id === $d3com->validate_id( $external_link_id ) ) {

```

int型への型変換はずすと問題なくなります。
ここでint型変換しなくてもvalidate_idメソッドでサニタイズすると思うので、int型変換無しでも良いと思うのですがどうでしょうか？

**Comment by naao** [comment]
nao-ponさん実装いただきありがとうございます！
